"""Dependency data source abstraction.

``DependencyProvider`` is the seam for fetching the bundled/third-party
dependency catalog. ``StaticDependencyProvider`` returns the catalog known at
build time; ``ReportFileDependencyProvider`` reads the ``pip-licenses`` JSON
report generated by ``make licenses-report`` (see eclipse_compositor/resources.py),
falling back to the static catalog if the report is missing or unreadable.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from eclipse_compositor.ui.licenses import license_texts as texts
from eclipse_compositor.ui.licenses.models import Dependency, License

logger = logging.getLogger(__name__)


class DependencyProvider(Protocol):
    """Supplies the list of dependencies to display."""

    def fetch(self) -> tuple[Dependency, ...]:
        """Return the current dependency catalog."""
        ...


class StaticDependencyProvider:
    """Hardcoded fallback catalog, used until dynamic fetching is wired up."""

    def fetch(self) -> tuple[Dependency, ...]:
        lgpl = License("GNU Lesser General Public License v3.0", texts.LGPL_V3)
        mit = License("MIT License", texts.MIT_LICENSE)
        bsd = License("BSD 3-Clause License", texts.BSD_3_CLAUSE)
        ffmpeg_licenses = (
            License("GNU Lesser General Public License v2.1+ / GPL v2+", texts.LGPL_V3),
            License("FFmpeg licensing notice", texts.FFMPEG_NOTICE),
        )
        return (
            Dependency(
                name="EklipsComposer",
                developer="Alexis ANEAS",
                repository_url="https://github.com/HalTobin/EklipsComposer",
                licenses=(mit,),
            ),
            Dependency(
                name="PySide6",
                developer="The Qt Company",
                repository_url="https://github.com/pyside/pyside-setup",
                licenses=(lgpl,),
            ),
            Dependency(
                name="Qt",
                developer="The Qt Company",
                repository_url="https://github.com/qt/qtbase",
                licenses=(lgpl,),
            ),
            Dependency(
                name="NumPy",
                developer="NumPy Developers",
                repository_url="https://github.com/numpy/numpy",
                licenses=(bsd,),
            ),
            Dependency(
                name="Pillow",
                developer="Pillow contributors",
                repository_url="https://github.com/python-pillow/Pillow",
                licenses=(mit,),
            ),
            Dependency(
                name="piexif",
                developer="hMatoba",
                repository_url="https://github.com/hMatoba/piexif",
                licenses=(mit,),
            ),
            Dependency(
                name="FFmpeg",
                developer="FFmpeg team",
                repository_url="https://github.com/FFmpeg/FFmpeg",
                licenses=ffmpeg_licenses,
            ),
        )


def _default_report_path() -> Path:
    from eclipse_compositor.resources import licenses_report_path

    return licenses_report_path()


@dataclass(frozen=True)
class ReportFileDependencyProvider:
    """Reads the ``pip-licenses`` JSON report generated by ``make licenses-report``."""

    path: Path = field(default_factory=_default_report_path)
    fallback: DependencyProvider = field(default_factory=StaticDependencyProvider)

    def fetch(self) -> tuple[Dependency, ...]:
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("Could not read licenses report at %s: %s", self.path, exc)
            return self.fallback.fetch()
        if not isinstance(raw, list):
            logger.warning("Unexpected licenses report format at %s", self.path)
            return self.fallback.fetch()
        dependencies = tuple(
            self._to_dependency(entry) for entry in raw if isinstance(entry, dict)
        )
        return dependencies or self.fallback.fetch()

    @staticmethod
    def _to_dependency(entry: dict) -> Dependency:
        """Map one ``pip-licenses`` JSON record to a ``Dependency``."""

        def _clean(value: object, *, default: str) -> str:
            text = str(value or "").strip()
            return default if not text or text.upper() == "UNKNOWN" else text

        name = _clean(entry.get("Name"), default="Unknown dependency")
        developer = _clean(entry.get("Author"), default="Unknown")
        repository_url = _clean(entry.get("URL"), default="")
        license_name = _clean(entry.get("License"), default="Unknown license")
        license_text = _clean(entry.get("LicenseText"), default="License text not available.")
        return Dependency(
            name=name,
            developer=developer,
            repository_url=repository_url,
            licenses=(License(name=license_name, text=license_text),),
        )

